### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by aaronmallen** [aaronmallen/activeinteractor#7]
Increase project test coverage to at least 95%

- [ ] #4 Increase test coverage of lib/active_interactor/context.rb
- [x] #5 Increase test coverage of lib/active_interactor/interactor/worker.rb
- [x] #6 Increase test coverage of lib/active_interactor/organizer.rb
- [ ] #8 Test lib/rails/generators
- [x] #9 Exclude config files from codeclimate
